apiVersion: batch/v1
kind: Job
metadata:
  name: hbase-bench-3pod-pod1
  namespace: default
  labels:
    app: hbase-benchmark
    cluster: j-395KBAFSTTCD3
    phase: 3pod-bench
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 0
  ttlSecondsAfterFinished: 604800
  template:
    metadata:
      labels:
        app: hbase-benchmark
        phase: 3pod-bench
        pod-index: "1"
    spec:
      nodeSelector:
        alpha.eksctl.io/nodegroup-name: mng-mytest-m7i-xl
      tolerations:
        - operator: Exists
      restartPolicy: Never
      volumes:
        - name: hbase-config
          configMap:
            name: hbase-site
      containers:
        - name: ycsb
          image: 812046859005.dkr.ecr.us-east-1.amazonaws.com/hbase-benchmark:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: hbase-config
              mountPath: /opt/ycsb/conf/hbase-site.xml
              subPath: hbase-site.xml
          env:
            - name: THREADS
              value: "100"
            - name: TABLE
              value: "usertable_bench"
            - name: ROWS_PER_POD
              value: "360000000"
            - name: TOTAL_PODS
              value: "3"
            - name: POD_INDEX
              value: "1"
          resources:
            requests:
              cpu: "2"
              memory: "6Gi"
            limits:
              cpu: "3"
              memory: "8Gi"
