apiVersion: batch/v1
kind: Job
metadata:
  name: hbase-bench-10pod-nowal-1tb-v2
  namespace: default
  labels:
    app: hbase-benchmark
    phase: 10pod-nowal-1tb-v2
spec:
  completions: 10
  parallelism: 10
  completionMode: Indexed
  backoffLimit: 1
  ttlSecondsAfterFinished: 86400
  template:
    metadata:
      labels:
        app: hbase-benchmark
        phase: 10pod-nowal-1tb-v2
    spec:
      nodeSelector:
        alpha.eksctl.io/nodegroup-name: mng-mytest-m7i-xl
      tolerations:
        - operator: Exists
      restartPolicy: Never
      containers:
        - name: ycsb
          image: 812046859005.dkr.ecr.us-east-1.amazonaws.com/hbase-benchmark:latest
          imagePullPolicy: Always
          env:
            - name: THREADS
              value: "100"
            - name: TABLE
              value: "usertable_r8g"
            - name: ROWS_PER_POD
              value: "100000000"
            - name: KEY_PREFIX_TAG
              value: "nowal"
            - name: POD_INDEX
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['batch.kubernetes.io/job-completion-index']
          resources:
            requests:
              cpu: "2"
              memory: "6Gi"
            limits:
              cpu: "3"
              memory: "8Gi"
