apiVersion: batch/v1
kind: Job
metadata:
  name: hbase-bench-1pod-wal
  namespace: default
  labels:
    app: hbase-benchmark
    phase: 1pod-wal
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 0
  ttlSecondsAfterFinished: 86400
  template:
    metadata:
      labels:
        app: hbase-benchmark
        phase: 1pod-wal
    spec:
      nodeSelector:
        alpha.eksctl.io/nodegroup-name: mng-mytest-m7i-xl
      tolerations:
        - operator: Exists
      restartPolicy: Never
      containers:
        - name: ycsb
          image: 812046859005.dkr.ecr.us-east-1.amazonaws.com/hbase-benchmark:latest
          imagePullPolicy: Always
          env:
            - name: THREADS
              value: "100"
            - name: TABLE
              value: "usertable_r8g"
            - name: ROWS_PER_POD
              value: "100000000"
            - name: TOTAL_PODS
              value: "1"
            - name: POD_INDEX
              value: "0"
          resources:
            requests:
              cpu: "2"
              memory: "6Gi"
            limits:
              cpu: "3"
              memory: "8Gi"
